![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Créez vos premiers arrays avec Numpy

Tout au long de ce cours, nous allons nous mettre dans la peau d’une personne travaillant  dans un service data au sein d'une banque. Plus précisément, vous travaillez pour la filière gérant les différents prêts. L’objectif sera d’utiliser les connaissances acquises sur les librairies Python pour aider l’agence dans différentes tâches.

Pour cette première tâche, nous avons à notre disposition les revenus de 10 clients de notre banque. Vous aurez à utiliser les différentes manipulations présentées dans ce chapitre pour sélectionner certains revenus selon une condition spécifique et effectuer diverses opérations.

In [1]:
import numpy as np

Considérons les revenus mensuels suivants :

In [2]:
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

A partir de ces revenus, créez un array que vous nommerez `revenus` :

In [3]:
revenus = np.array(liste)
display(revenus)

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

Maintenant, créez un nouvel array `haut_revenus` dans lequel vous sélectionnerez l'ensemble des revenus supérieurs ou égal à 3000€ :

In [4]:
haut_revenus = revenus[revenus>=3000]
display(haut_revenus)

array([3000, 5000])

 <div class="alert alert-warning" role="alert">
  Notez qu'en python vous pouvez utiliser le '_' aka 'underscore' comme <strong>séparateur de milliers</strong>. En effet, '1 000 000' est plus facile à lire que '1000000'.
</div>

In [5]:
haut_revenus = revenus[revenus>=3_000]
haut_revenus

array([3000, 5000])

Il est à présent temps de calculer quelques indicateurs :
- calculez dans un premier temps la somme des revenus **annuelle**. Pour rappel, les revenus listés ci dessus sont mensuels.
- calculez ensuite la moyenne des revenus des 10 clients

In [6]:
# On calcule la somme :

somme_sum = revenus.sum()
somme_sum

20672

In [7]:
# On multiplie par 12 :

somme = somme_sum * 12
somme

248064

 <div class="alert alert-info" role="info">
Dans les premiers temps, il est bon de bien <strong>décomposer</strong> son code. Ecrire plusieurs lignes, passer par des "<em>variables intermédiaires</em>" et bien controler le résultat de chaque commande vous permettra d'éviter les <strong>erreurs</strong>, de prendre <strong>confiance</strong> dans votre code et de mieux <strong>maîtriser</strong> vos acquis.
</div>
 <div class="alert alert-info" role="info">
Dans un second temps, vous pourrez commencer à <strong>factoriser</strong> votre code, c'est à dire le "<em>compresser</em>": écrire plusieurs lignes en une seule, sans passer par des variables intermédiaires.
</div>

In [8]:
# Il était donc possible de faire les 2 opérations en une ligne :

somme = revenus.sum() * 12
print("La somme des revenus annuelle est :", somme, "€")

La somme des revenus annuelle est : 248064 €


 <div class="alert alert-warning" role="alert">
  Dans certains cas, l'<strong>ordre des opérations</strong> n'a pas d'influence sur le résultat.
</div>

In [9]:
# En effet, on pouvait aussi faire :

revenus_12 = revenus * 12
revenus_12

array([21600, 18000, 26400, 36000, 26064, 60000, 16800, 14400, 13200,
       15600])

In [10]:
somme = revenus_12.sum()
somme

248064

Enfin, en général, on note les "grosses" sommes en K€ ou en M€. Cela est plus facile à lire. De plus, votre interlocuteur retiendra plus volontier l'ordre de grandeur d'un chiffre ou même un chiffre 'rond' qu'un chiffre trop détaillé...

In [ ]:
# Par exemple :

somme_K = round(somme / 1000)
print("La somme des revenus annuelle est :", somme_K, "K€")

In [ ]:
# Voire même :

print("La somme des revenus annuelle est d'environ:", 250, "K€")

In [ ]:
# Ou encore :

somme_M = round(somme / 1_000_000,2)
print("La somme des revenus annuelle est :", somme_M, "M€")

Passons à la moyenne

In [11]:
moyenne = revenus.mean()
print("La moyenne des revenus mensuelle est :", moyenne, "€")

La moyenne des revenus mensuelle est : 2067.2 €


In [ ]:
# Ou encore :

moyenne = round(moyenne)
print("La moyenne des revenus mensuelle est :", moyenne, "€")

Un de nos clients (dont les revenus mensuels s'élevaient jusque là à 1400€) vient de nous annoncer qu'il venait d'obtenir une promotion. Grâce à cette dernière, il a gagné 200€ sur son salaire mensuel. Effectuez cette modification au sein de votre array revenus.

In [ ]:
print("Array avant :", revenus)

revenus[revenus == 1400] = 1600
print("Array après :", revenus)

La modification a bien été effectuée.

Pour expliciter un peu plus cette ligne de code :
- `revenus[revenus == 1400]` vient sélectionner l'ensemble des éléments qui sont strictement égals à 1400€ (donc ici le seul qui nous intéresse)
- la suite vient modifier cet élement par la nouvelle valeur (ici 1600)

Dans le cas de cette opération on pouvait utiliser également l'opérateur '+=' en écrivant `revenus[revenus == 1400] += 200`